# Generated by Django 3.2.13 on 2022-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armand_api', '0002_db_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_proj_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('des', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('creator', models.IntegerField(default=0)),
                ('updator', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
