# Generated by Django 3.2.13 on 2022-06-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armand_api', '0003_db_proj_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_proj_list',
            name='Group',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='Logon_var',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='Permission',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='Public_var',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='hide_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='mock_type',
            field=models.CharField(blank=True, default='mock_data', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_proj_list',
            name='sign',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
